name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 18
  GATSBY_CLI_VERSION: 4.17.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@${{ env.GATSBY_CLI_VERSION }}

      - name: Build
        run: gatsby build

      -run: |
        az storage blob upload-batch -s public -d '$web' --account-name nateisthename --overwrite
